import { StoreData } from "@/lib/types";

const now = "2026-03-31T10:00:00.000Z";

export const seedData: StoreData = {
  settings: {
    brandName: "Risol Club",
    story:
      "Risol Club adalah dapur kecil yang serius soal rasa nyaman: kulit risol lembut, isian royal, dan vibe handmade yang hangat buat teman ngemil, hadiah kecil, atau stok mood booster.",
    storyEn:
      "Risol Club is a cozy small-batch kitchen focused on comforting flavors, generous fillings, and handmade warmth for gifting, snacking, and little joyful moments.",
    pickupAddress:
      "Pickup point akan dikonfirmasi lewat WhatsApp setelah pembayaran diverifikasi.",
    pickupAddressEn:
      "Pickup point details will be confirmed via WhatsApp after payment verification.",
    bankName: "BCA",
    bankAccountNumber: "1234567890",
    bankAccountHolder: "Risol Club",
    sellerWhatsapp: "6285183151407",
    sellerWhatsappDisplay: "085183151407",
    defaultDeliveryFee: 0,
  },
  suppliers: [
    {
      id: "sup-1",
      name: "Toko Sembako Harmoni",
      contact: "Pak Andi - 0812-1111-1111",
      notes: "Supplier utama bahan dasar.",
      isActive: true,
      createdAt: now,
    },
    {
      id: "sup-2",
      name: "Kios Pastry Pelangi",
      contact: "Bu Intan - 0812-2222-2222",
      notes: "Sering dipakai untuk coklat dan mayo premium.",
      isActive: true,
      createdAt: now,
    },
  ],
  ingredients: [
    {
      id: "ing-1",
      name: "Kulit risol",
      unit: "lembar",
      stock: 48,
      lowStockThreshold: 20,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-2",
      name: "Mayonnaise",
      unit: "gram",
      stock: 1800,
      lowStockThreshold: 500,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-3",
      name: "Smoked beef",
      unit: "gram",
      stock: 900,
      lowStockThreshold: 300,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-4",
      name: "Keju",
      unit: "gram",
      stock: 950,
      lowStockThreshold: 300,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-5",
      name: "Coklat filling",
      unit: "gram",
      stock: 1200,
      lowStockThreshold: 400,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-6",
      name: "Breadcrumbs",
      unit: "gram",
      stock: 1600,
      lowStockThreshold: 400,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
  ],
  ingredientSupplierPrices: [
    {
      id: "price-1",
      ingredientId: "ing-1",
      supplierId: "sup-1",
      pricePerUnit: 900,
      effectiveFrom: "2026-03-20",
      notes: "Batch weekly",
      createdAt: now,
    },
    {
      id: "price-2",
      ingredientId: "ing-2",
      supplierId: "sup-2",
      pricePerUnit: 0.08,
      effectiveFrom: "2026-03-19",
      notes: "Premium mayo pouch",
      createdAt: now,
    },
    {
      id: "price-3",
      ingredientId: "ing-3",
      supplierId: "sup-1",
      pricePerUnit: 0.12,
      effectiveFrom: "2026-03-18",
      notes: "Smoked beef slice bulk",
      createdAt: now,
    },
    {
      id: "price-4",
      ingredientId: "ing-4",
      supplierId: "sup-2",
      pricePerUnit: 0.11,
      effectiveFrom: "2026-03-19",
      notes: "Cheddar block",
      createdAt: now,
    },
    {
      id: "price-5",
      ingredientId: "ing-5",
      supplierId: "sup-2",
      pricePerUnit: 0.09,
      effectiveFrom: "2026-03-17",
      notes: "Chocolate spread",
      createdAt: now,
    },
    {
      id: "price-6",
      ingredientId: "ing-6",
      supplierId: "sup-1",
      pricePerUnit: 0.03,
      effectiveFrom: "2026-03-18",
      notes: "Fine breadcrumbs",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "prod-1",
      slug: "risol-mayo",
      name: "Risol Mayo",
      nameEn: "Mayo Risol",
      shortDescription: "Isi smoked beef, mayo, dan keju yang creamy-gurih.",
      shortDescriptionEn: "Smoked beef, mayo, and cheese with a creamy savory bite.",
      description:
        "Menu favorit dengan tekstur lembut di luar dan isian mayo-smoked beef yang lumer. Cocok untuk hampers kecil, coffee pairing, atau stok ngemil satu rumah.",
      descriptionEn:
        "A fan favorite with a tender wrapper and creamy mayo-smoked beef filling. Perfect for gifting, coffee pairings, or home snacking.",
      price: 18000,
      featured: true,
      isActive: true,
      accent: "from-rose-100 via-white to-orange-100",
      prepLabel: "Ready in 1 day pre-order",
      prepLabelEn: "1 day pre-order lead time",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prod-2",
      slug: "risol-coklat",
      name: "Risol Coklat",
      nameEn: "Chocolate Risol",
      shortDescription: "Manis, lembut, dan cocok buat dessert snack.",
      shortDescriptionEn: "Sweet, soft, and perfect as a dessert-style snack.",
      description:
        "Risol dessert dengan filling coklat yang lembut dan manisnya pas. Enak disajikan hangat untuk teman ngeteh atau hadiah kecil yang cute.",
      descriptionEn:
        "A dessert-style risol with soft chocolate filling and balanced sweetness. Best served warm for tea time or as a cute little gift.",
      price: 16000,
      featured: true,
      isActive: true,
      accent: "from-amber-100 via-white to-rose-100",
      prepLabel: "Ready in 1 day pre-order",
      prepLabelEn: "1 day pre-order lead time",
      createdAt: now,
      updatedAt: now,
    },
  ],
  recipes: [
    {
      id: "rec-1",
      productId: "prod-1",
      yieldCount: 1,
      items: [
        { ingredientId: "ing-1", quantity: 1 },
        { ingredientId: "ing-2", quantity: 45 },
        { ingredientId: "ing-3", quantity: 30 },
        { ingredientId: "ing-4", quantity: 15 },
        { ingredientId: "ing-6", quantity: 20 },
      ],
      updatedAt: now,
    },
    {
      id: "rec-2",
      productId: "prod-2",
      yieldCount: 1,
      items: [
        { ingredientId: "ing-1", quantity: 1 },
        { ingredientId: "ing-5", quantity: 55 },
        { ingredientId: "ing-6", quantity: 18 },
      ],
      updatedAt: now,
    },
  ],
  productStocks: [
    {
      productId: "prod-1",
      stock: 18,
      lowStockThreshold: 8,
      updatedAt: now,
    },
    {
      productId: "prod-2",
      stock: 12,
      lowStockThreshold: 8,
      updatedAt: now,
    },
  ],
  orders: [
    {
      id: "ord-1",
      code: "RC-3103-001",
      locale: "id",
      customerName: "Nadia",
      customerWhatsapp: "628111111111",
      fulfillmentMethod: "pickup",
      preorderDate: "2026-03-31T14:00:00.000Z",
      note: "Tolong kasih pita merah kalau bisa.",
      deliveryFee: 0,
      subtotal: 52000,
      total: 52000,
      status: "payment_review",
      items: [
        {
          productId: "prod-1",
          productName: "Risol Mayo",
          quantity: 2,
          unitPrice: 18000,
          costSnapshot: 11,
        },
        {
          productId: "prod-2",
          productName: "Risol Coklat",
          quantity: 1,
          unitPrice: 16000,
          costSnapshot: 6.49,
        },
      ],
      paymentProof: {
        fileName: "sample-proof.jpg",
        mimeType: "image/jpeg",
        dataUrl:
          "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgZmlsbD0iI2ZlZjJmMiIvPjx0ZXh0IHg9IjUwIiB5PSIxNTAiIGZvbnQtc2l6ZT0iMzAiIGZpbGw9IiNiOTFlMWUiPkJ1a3RpIHRyYW5zZmVyIHNhbXBsZTwvdGV4dD48L3N2Zz4=",
        uploadedAt: now,
      },
      createdAt: "2026-03-31T08:50:00.000Z",
      updatedAt: "2026-03-31T08:50:00.000Z",
    },
    {
      id: "ord-2",
      code: "RC-3003-004",
      locale: "id",
      customerName: "Tara",
      customerWhatsapp: "628222222222",
      fulfillmentMethod: "delivery",
      address: "Jl. Melati No. 12, Jakarta Selatan",
      preorderDate: "2026-03-30T12:00:00.000Z",
      note: "",
      deliveryFee: 10000,
      subtotal: 72000,
      total: 82000,
      status: "completed",
      items: [
        {
          productId: "prod-1",
          productName: "Risol Mayo",
          quantity: 4,
          unitPrice: 18000,
          costSnapshot: 11,
        },
      ],
      createdAt: "2026-03-29T12:10:00.000Z",
      updatedAt: "2026-03-30T13:30:00.000Z",
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Order baru perlu dicek",
      body: "Nadia upload bukti bayar untuk RC-3103-001.",
      href: "/seller/orders",
      read: false,
      createdAt: "2026-03-31T08:55:00.000Z",
    },
  ],
  inventoryMovements: [
    {
      id: "move-1",
      itemType: "product",
      itemId: "prod-1",
      type: "sale",
      quantity: -4,
      note: "Order RC-3003-004 completed",
      createdAt: "2026-03-30T13:30:00.000Z",
    },
    {
      id: "move-2",
      itemType: "ingredient",
      itemId: "ing-5",
      type: "restock",
      quantity: 800,
      note: "Supplier top-up",
      createdAt: "2026-03-29T09:00:00.000Z",
    },
  ],
};
