import { cloneImages, cloneVariants, DEFAULT_PACK_SIZE } from "@/lib/catalog";
import { StoreData } from "@/lib/types";

const now = "2026-03-31T10:00:00.000Z";

export const seedData: StoreData = {
  settings: {
    brandName: "Risol Club",
    story:
      "Risol Club adalah dapur kecil yang serius soal rasa nyaman: kulit risol lembut, isian royal, dan vibe handmade yang hangat buat teman ngemil, hadiah kecil, atau stok mood booster.",
    storyEn:
      "Risol Club is a cozy small-batch kitchen focused on comforting flavors, generous fillings, and handmade warmth for gifting, snacking, and little joyful moments.",
    pickupAddress:
      "Pickup point akan dikonfirmasi lewat WhatsApp setelah pembayaran diverifikasi.",
    pickupAddressEn:
      "Pickup point details will be confirmed via WhatsApp after payment verification.",
    bankName: "BCA",
    bankAccountNumber: "6050584265",
    bankAccountHolder: "Lubna Aqila",
    sellerWhatsapp: "6285183151407",
    sellerWhatsappDisplay: "085183151407",
    defaultDeliveryFee: 0,
  },
  suppliers: [
    {
      id: "sup-1",
      name: "Toko Sembako Harmoni",
      contact: "Pak Andi - 0812-1111-1111",
      notes: "Supplier utama bahan dasar.",
      isActive: true,
      createdAt: now,
    },
    {
      id: "sup-2",
      name: "Kios Pastry Pelangi",
      contact: "Bu Intan - 0812-2222-2222",
      notes: "Sering dipakai untuk coklat dan mayo premium.",
      isActive: true,
      createdAt: now,
    },
  ],
  ingredients: [
    {
      id: "ing-1",
      name: "Kulit risol",
      unit: "lembar",
      stock: 48,
      lowStockThreshold: 20,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-2",
      name: "Mayonnaise",
      unit: "gram",
      stock: 1800,
      lowStockThreshold: 500,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-3",
      name: "Smoked beef",
      unit: "gram",
      stock: 900,
      lowStockThreshold: 300,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-4",
      name: "Keju",
      unit: "gram",
      stock: 950,
      lowStockThreshold: 300,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-5",
      name: "Coklat filling",
      unit: "gram",
      stock: 1200,
      lowStockThreshold: 400,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-6",
      name: "Breadcrumbs",
      unit: "gram",
      stock: 1600,
      lowStockThreshold: 400,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
  ],
  ingredientSupplierPrices: [
    {
      id: "price-1",
      ingredientId: "ing-1",
      supplierId: "sup-1",
      pricePerUnit: 900,
      effectiveFrom: "2026-03-20",
      notes: "Batch weekly",
      createdAt: now,
    },
    {
      id: "price-2",
      ingredientId: "ing-2",
      supplierId: "sup-2",
      pricePerUnit: 0.08,
      effectiveFrom: "2026-03-19",
      notes: "Premium mayo pouch",
      createdAt: now,
    },
    {
      id: "price-3",
      ingredientId: "ing-3",
      supplierId: "sup-1",
      pricePerUnit: 0.12,
      effectiveFrom: "2026-03-18",
      notes: "Smoked beef slice bulk",
      createdAt: now,
    },
    {
      id: "price-4",
      ingredientId: "ing-4",
      supplierId: "sup-2",
      pricePerUnit: 0.11,
      effectiveFrom: "2026-03-19",
      notes: "Cheddar block",
      createdAt: now,
    },
    {
      id: "price-5",
      ingredientId: "ing-5",
      supplierId: "sup-2",
      pricePerUnit: 0.09,
      effectiveFrom: "2026-03-17",
      notes: "Chocolate spread",
      createdAt: now,
    },
    {
      id: "price-6",
      ingredientId: "ing-6",
      supplierId: "sup-1",
      pricePerUnit: 0.03,
      effectiveFrom: "2026-03-18",
      notes: "Fine breadcrumbs",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "prod-1",
      slug: "smoked-beef-mayo",
      name: "Smoked Beef Mayo",
      nameEn: "Smoked Beef Mayo",
      shortDescription:
        "Isi smoked beef, mayo, cheese, dan egg yang gurih creamy dalam pack isi 3 pcs.",
      shortDescriptionEn:
        "A creamy savory trio with smoked beef, mayo, cheese, and egg in a 3-piece pack.",
      description:
        "Smoked Beef Mayo jadi menu comfort snack yang paling aman buat ramai-ramai. Rasanya gurih, creamy, dan familiar, dengan format 1 qty = 3 pcs jadi enak buat stok freezer ataupun langsung digoreng hangat buat nyemil sore 😊🙌",
      descriptionEn:
        "Smoked Beef Mayo is the crowd-pleasing comfort snack: savory, creamy, familiar, and sold in 3-piece packs that work well for freezer stock or a warm fried snack.",
      price: 28000,
      featured: true,
      isActive: true,
      accent: "from-[#ffe4dd] via-white to-[#ffd9c6]",
      prepLabel: "Pre-order batch • 1 qty = 3 pcs",
      prepLabelEn: "Pre-order batch • 1 qty = 3 pcs",
      packSize: DEFAULT_PACK_SIZE,
      variants: cloneVariants([
        { type: "frozen", label: "Frozen", price: 28000 },
        { type: "fried", label: "Fried", price: 30000 },
      ]),
      images: cloneImages(
        [
          "/catalog/smoked-beef-mayo/01.jpeg",
          "/catalog/smoked-beef-mayo/02.jpeg",
          "/catalog/smoked-beef-mayo/03.jpeg",
        ],
        "Smoked Beef Mayo",
      ),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prod-2",
      slug: "choco-cheese",
      name: "Choco Cheese",
      nameEn: "Choco Cheese",
      shortDescription:
        "Cokelat renyah yang ketemu keju lembut, manis-gurihnya bikin susah berhenti.",
      shortDescriptionEn:
        "Chocolate crunch meets soft cheese in a sweet-savory pack that is hard to stop eating.",
      description:
        "Risol Choco Cheese hadir buat kamu yang suka dessert snack dengan tekstur playful. Ada sensasi crunchy cokelat, ada lembut keju, dan setiap 1 qty selalu datang dalam 1 pack isi 3 pcs yang cocok buat dibagi atau dimakan sendiri pelan-pelan 😊🙌",
      descriptionEn:
        "Choco Cheese Risol is made for playful dessert-snack cravings. Expect a chocolate crunch, a soft cheese finish, and 1 order quantity always packed as 3 pieces for sharing or savoring slowly.",
      price: 28000,
      featured: true,
      isActive: true,
      accent: "from-[#fff0df] via-white to-[#ffe4d8]",
      prepLabel: "Pre-order batch • 1 qty = 3 pcs",
      prepLabelEn: "Pre-order batch • 1 qty = 3 pcs",
      packSize: DEFAULT_PACK_SIZE,
      variants: cloneVariants([
        { type: "frozen", label: "Frozen", price: 28000 },
        { type: "fried", label: "Fried", price: 30000 },
      ]),
      images: cloneImages(
        [
          "/catalog/choco-cheese/01.jpeg",
          "/catalog/choco-cheese/02.jpeg",
          "/catalog/choco-cheese/03.jpeg",
        ],
        "Choco Cheese",
      ),
      createdAt: now,
      updatedAt: now,
    },
  ],
  recipes: [
    {
      id: "rec-1",
      productId: "prod-1",
      yieldCount: 1,
      items: [
        { ingredientId: "ing-1", quantity: 1 },
        { ingredientId: "ing-2", quantity: 45 },
        { ingredientId: "ing-3", quantity: 30 },
        { ingredientId: "ing-4", quantity: 15 },
        { ingredientId: "ing-6", quantity: 20 },
      ],
      updatedAt: now,
    },
    {
      id: "rec-2",
      productId: "prod-2",
      yieldCount: 1,
      items: [
        { ingredientId: "ing-1", quantity: 1 },
        { ingredientId: "ing-5", quantity: 55 },
        { ingredientId: "ing-6", quantity: 18 },
      ],
      updatedAt: now,
    },
  ],
  productStocks: [
    {
      productId: "prod-1",
      stock: 18,
      lowStockThreshold: 8,
      updatedAt: now,
    },
    {
      productId: "prod-2",
      stock: 12,
      lowStockThreshold: 8,
      updatedAt: now,
    },
  ],
  orders: [
    {
      id: "ord-1",
      code: "RC-3103-001",
      source: "web",
      locale: "id",
      customerName: "Nadia",
      customerWhatsapp: "628111111111",
      fulfillmentMethod: "pickup",
      preorderDate: "2026-03-31T14:00:00.000Z",
      note: "Tolong kasih pita merah kalau bisa.",
      deliveryFee: 0,
      subtotal: 52000,
      total: 52000,
      status: "payment_review",
      items: [
        {
          productId: "prod-1",
          productName: "Smoked Beef Mayo",
          variantType: "fried",
          variantLabel: "Fried",
          quantity: 2,
          pieceCount: 6,
          unitPrice: 30000,
          costSnapshot: 32.4,
        },
        {
          productId: "prod-2",
          productName: "Choco Cheese",
          variantType: "frozen",
          variantLabel: "Frozen",
          quantity: 1,
          pieceCount: 3,
          unitPrice: 28000,
          costSnapshot: 9.81,
        },
      ],
      paymentProof: {
        fileName: "sample-proof.jpg",
        mimeType: "image/jpeg",
        dataUrl:
          "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgZmlsbD0iI2ZlZjJmMiIvPjx0ZXh0IHg9IjUwIiB5PSIxNTAiIGZvbnQtc2l6ZT0iMzAiIGZpbGw9IiNiOTFlMWUiPkJ1a3RpIHRyYW5zZmVyIHNhbXBsZTwvdGV4dD48L3N2Zz4=",
        uploadedAt: now,
      },
      createdAt: "2026-03-31T08:50:00.000Z",
      updatedAt: "2026-03-31T08:50:00.000Z",
    },
    {
      id: "ord-2",
      code: "RC-3003-004",
      source: "web",
      locale: "id",
      customerName: "Tara",
      customerWhatsapp: "628222222222",
      fulfillmentMethod: "delivery",
      address: "Jl. Melati No. 12, Jakarta Selatan",
      preorderDate: "2026-03-30T12:00:00.000Z",
      note: "",
      deliveryFee: 10000,
      subtotal: 72000,
      total: 82000,
      status: "completed",
      items: [
        {
          productId: "prod-1",
          productName: "Smoked Beef Mayo",
          variantType: "frozen",
          variantLabel: "Frozen",
          quantity: 4,
          pieceCount: 12,
          unitPrice: 28000,
          costSnapshot: 32.4,
        },
      ],
      createdAt: "2026-03-29T12:10:00.000Z",
      updatedAt: "2026-03-30T13:30:00.000Z",
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Order baru perlu dicek",
      body: "Nadia upload bukti bayar untuk RC-3103-001.",
      href: "/seller/orders",
      read: false,
      createdAt: "2026-03-31T08:55:00.000Z",
    },
  ],
  inventoryMovements: [
    {
      id: "move-1",
      itemType: "product",
      itemId: "prod-1",
      type: "sale",
      quantity: -4,
      note: "Order RC-3003-004 completed",
      createdAt: "2026-03-30T13:30:00.000Z",
    },
    {
      id: "move-2",
      itemType: "ingredient",
      itemId: "ing-5",
      type: "restock",
      quantity: 800,
      note: "Supplier top-up",
      createdAt: "2026-03-29T09:00:00.000Z",
    },
  ],
};
