import { cloneImages, cloneVariants, DEFAULT_PACK_SIZE } from "@/lib/catalog";
import { StoreData } from "@/lib/types";

const now = "2026-03-31T10:00:00.000Z";
const SMILING_HANDS_EMOJI = "\u{1F60A}\u{1F64C}";
const MIDDLE_DOT = "\u00b7";

export const seedData: StoreData = {
  settings: {
    brandName: "Risol Club",
    story:
      "Risol Club adalah dapur kecil yang serius soal rasa nyaman: kulit risol lembut, isian royal, dan vibe handmade yang hangat buat teman ngemil, hadiah kecil, atau stok mood booster.",
    storyEn:
      "Risol Club is a cozy small-batch kitchen focused on comforting flavors, generous fillings, and handmade warmth for gifting, snacking, and little joyful moments.",
    pickupAddress:
      "Pickup point akan dikonfirmasi lewat WhatsApp setelah pembayaran diverifikasi.",
    pickupAddressEn:
      "Pickup point details will be confirmed via WhatsApp after payment verification.",
    bankName: "BCA",
    bankAccountNumber: "6050584265",
    bankAccountHolder: "Lubna Aqila",
    sellerWhatsapp: "62881081767677",
    sellerWhatsappDisplay: "(0881081767677)",
    defaultDeliveryFee: 0,
  },
  suppliers: [
    {
      id: "sup-1",
      name: "Depo Baking",
      contact: "",
      notes: "Dipakai untuk estimasi belanja bahan inti dan packaging harian.",
      isActive: true,
      createdAt: now,
    },
    {
      id: "sup-2",
      name: "Toko Aroma",
      contact: "",
      notes: "Dipakai untuk estimasi belanja bahan inti dan packaging harian.",
      isActive: true,
      createdAt: now,
    },
  ],
  ingredients: [
    {
      id: "ing-1",
      name: "Tepung terigu",
      unit: "gram",
      stock: 4000,
      lowStockThreshold: 1000,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-2",
      name: "Tepung tapioka",
      unit: "gram",
      stock: 1500,
      lowStockThreshold: 400,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-3",
      name: "Telur",
      unit: "butir",
      stock: 40,
      lowStockThreshold: 10,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-4",
      name: "Garam",
      unit: "gram",
      stock: 500,
      lowStockThreshold: 100,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-5",
      name: "Air",
      unit: "ml",
      stock: 5000,
      lowStockThreshold: 1000,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-6",
      name: "Minyak sawit",
      unit: "ml",
      stock: 2000,
      lowStockThreshold: 500,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-7",
      name: "Tepung roti",
      unit: "gram",
      stock: 2500,
      lowStockThreshold: 500,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-8",
      name: "Cocoa powder",
      unit: "gram",
      stock: 300,
      lowStockThreshold: 50,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-9",
      name: "Pewarna makanan",
      unit: "ml",
      stock: 60,
      lowStockThreshold: 10,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-10",
      name: "Mayonnaise",
      unit: "gram",
      stock: 2000,
      lowStockThreshold: 400,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-11",
      name: "Susu kental manis",
      unit: "gram",
      stock: 1200,
      lowStockThreshold: 250,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-12",
      name: "Keju",
      unit: "gram",
      stock: 1800,
      lowStockThreshold: 300,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-13",
      name: "Smoked beef",
      unit: "gram",
      stock: 1200,
      lowStockThreshold: 300,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-14",
      name: "Crunchy choco filling",
      unit: "gram",
      stock: 2000,
      lowStockThreshold: 400,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
    {
      id: "ing-15",
      name: "Plastic bag",
      unit: "pcs",
      stock: 300,
      lowStockThreshold: 60,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-16",
      name: "Sticker print",
      unit: "pcs",
      stock: 300,
      lowStockThreshold: 60,
      activeSupplierId: "sup-1",
      createdAt: now,
    },
    {
      id: "ing-17",
      name: "Plastic container",
      unit: "pcs",
      stock: 300,
      lowStockThreshold: 60,
      activeSupplierId: "sup-2",
      createdAt: now,
    },
  ],
  ingredientSupplierPrices: [
    {
      id: "price-1",
      ingredientId: "ing-1",
      supplierId: "sup-1",
      pricePerUnit: 10,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-2",
      ingredientId: "ing-2",
      supplierId: "sup-2",
      pricePerUnit: 14,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-3",
      ingredientId: "ing-3",
      supplierId: "sup-1",
      pricePerUnit: 2800,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per butir",
      createdAt: now,
    },
    {
      id: "price-4",
      ingredientId: "ing-4",
      supplierId: "sup-2",
      pricePerUnit: 2,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-5",
      ingredientId: "ing-5",
      supplierId: "sup-1",
      pricePerUnit: 1,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per ml",
      createdAt: now,
    },
    {
      id: "price-6",
      ingredientId: "ing-6",
      supplierId: "sup-2",
      pricePerUnit: 18,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per ml",
      createdAt: now,
    },
    {
      id: "price-7",
      ingredientId: "ing-7",
      supplierId: "sup-1",
      pricePerUnit: 22,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-8",
      ingredientId: "ing-8",
      supplierId: "sup-2",
      pricePerUnit: 95,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-9",
      ingredientId: "ing-9",
      supplierId: "sup-1",
      pricePerUnit: 150,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per ml",
      createdAt: now,
    },
    {
      id: "price-10",
      ingredientId: "ing-10",
      supplierId: "sup-2",
      pricePerUnit: 20,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-11",
      ingredientId: "ing-11",
      supplierId: "sup-1",
      pricePerUnit: 28,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-12",
      ingredientId: "ing-12",
      supplierId: "sup-2",
      pricePerUnit: 77,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-13",
      ingredientId: "ing-13",
      supplierId: "sup-1",
      pricePerUnit: 120,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-14",
      ingredientId: "ing-14",
      supplierId: "sup-2",
      pricePerUnit: 117,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per gram",
      createdAt: now,
    },
    {
      id: "price-15",
      ingredientId: "ing-15",
      supplierId: "sup-1",
      pricePerUnit: 150,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per pcs",
      createdAt: now,
    },
    {
      id: "price-16",
      ingredientId: "ing-16",
      supplierId: "sup-1",
      pricePerUnit: 500,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per pcs",
      createdAt: now,
    },
    {
      id: "price-17",
      ingredientId: "ing-17",
      supplierId: "sup-2",
      pricePerUnit: 1008,
      effectiveFrom: "2026-04-05",
      notes: "Estimasi per pcs",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "prod-1",
      slug: "smoked-beef-mayo",
      name: "Smoked Beef Mayo",
      nameEn: "Smoked Beef Mayo",
      shortDescription:
        "Isi smoked beef, mayo, cheese, dan egg yang gurih creamy dalam pack isi 3 pcs.",
      shortDescriptionEn:
        "A creamy savory trio with smoked beef, mayo, cheese, and egg in a 3-piece pack.",
      description:
        `Smoked Beef Mayo jadi menu comfort snack yang paling aman buat ramai-ramai. Rasanya gurih, creamy, dan familiar, dengan format 1 qty = 3 pcs jadi enak buat stok freezer ataupun langsung digoreng hangat buat nyemil sore ${SMILING_HANDS_EMOJI}`,
      descriptionEn:
        "Smoked Beef Mayo is the crowd-pleasing comfort snack: savory, creamy, familiar, and sold in 3-piece packs that work well for freezer stock or a warm fried snack.",
      price: 28000,
      featured: true,
      isActive: true,
      accent: "from-[#ffe4dd] via-white to-[#ffd9c6]",
      prepLabel: `Pre-order batch ${MIDDLE_DOT} 1 qty = 3 pcs`,
      prepLabelEn: `Pre-order batch ${MIDDLE_DOT} 1 qty = 3 pcs`,
      packSize: DEFAULT_PACK_SIZE,
      variants: cloneVariants([
        { type: "frozen", label: "Frozen", price: 28000 },
        { type: "fried", label: "Fried", price: 30000 },
      ]),
      images: cloneImages(
        [
          "/catalog/smoked-beef-mayo/01.jpeg",
          "/catalog/smoked-beef-mayo/02.jpeg",
          "/catalog/smoked-beef-mayo/03.jpeg",
        ],
        "Smoked Beef Mayo",
      ),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prod-2",
      slug: "choco-cheese",
      name: "Choco Cheese",
      nameEn: "Choco Cheese",
      shortDescription:
        "Cokelat renyah yang ketemu keju lembut, manis-gurihnya bikin susah berhenti.",
      shortDescriptionEn:
        "Chocolate crunch meets soft cheese in a sweet-savory pack that is hard to stop eating.",
      description:
        `Risol Choco Cheese hadir buat kamu yang suka dessert snack dengan tekstur playful. Ada sensasi crunchy cokelat, ada lembut keju, dan setiap 1 qty selalu datang dalam 1 pack isi 3 pcs yang cocok buat dibagi atau dimakan sendiri pelan-pelan ${SMILING_HANDS_EMOJI}`,
      descriptionEn:
        "Choco Cheese Risol is made for playful dessert-snack cravings. Expect a chocolate crunch, a soft cheese finish, and 1 order quantity always packed as 3 pieces for sharing or savoring slowly.",
      price: 28000,
      featured: true,
      isActive: true,
      accent: "from-[#fff0df] via-white to-[#ffe4d8]",
      prepLabel: `Pre-order batch ${MIDDLE_DOT} 1 qty = 3 pcs`,
      prepLabelEn: `Pre-order batch ${MIDDLE_DOT} 1 qty = 3 pcs`,
      packSize: DEFAULT_PACK_SIZE,
      variants: cloneVariants([
        { type: "frozen", label: "Frozen", price: 28000 },
        { type: "fried", label: "Fried", price: 30000 },
      ]),
      images: cloneImages(
        [
          "/catalog/choco-cheese/01.jpeg",
          "/catalog/choco-cheese/02.jpeg",
          "/catalog/choco-cheese/03.jpeg",
        ],
        "Choco Cheese",
      ),
      createdAt: now,
      updatedAt: now,
    },
  ],
  recipes: [
    {
      id: "rec-1",
      productId: "prod-1",
      yieldCount: 1,
      items: [
        { ingredientId: "ing-1", quantity: 15 },
        { ingredientId: "ing-2", quantity: 5 },
        { ingredientId: "ing-3", quantity: 0.4 },
        { ingredientId: "ing-4", quantity: 1 },
        { ingredientId: "ing-5", quantity: 20 },
        { ingredientId: "ing-6", quantity: 8 },
        { ingredientId: "ing-7", quantity: 10 },
        { ingredientId: "ing-10", quantity: 14 },
        { ingredientId: "ing-11", quantity: 4 },
        { ingredientId: "ing-12", quantity: 8 },
        { ingredientId: "ing-13", quantity: 12 },
        { ingredientId: "ing-15", quantity: 0.333333 },
        { ingredientId: "ing-16", quantity: 0.333333 },
        { ingredientId: "ing-17", quantity: 0.333333 },
      ],
      updatedAt: now,
    },
    {
      id: "rec-2",
      productId: "prod-2",
      yieldCount: 1,
      items: [
        { ingredientId: "ing-1", quantity: 15 },
        { ingredientId: "ing-2", quantity: 5 },
        { ingredientId: "ing-3", quantity: 0.15 },
        { ingredientId: "ing-4", quantity: 1 },
        { ingredientId: "ing-5", quantity: 20 },
        { ingredientId: "ing-6", quantity: 8 },
        { ingredientId: "ing-7", quantity: 10 },
        { ingredientId: "ing-8", quantity: 3 },
        { ingredientId: "ing-9", quantity: 0.2 },
        { ingredientId: "ing-12", quantity: 8 },
        { ingredientId: "ing-14", quantity: 20 },
        { ingredientId: "ing-15", quantity: 0.333333 },
        { ingredientId: "ing-16", quantity: 0.333333 },
        { ingredientId: "ing-17", quantity: 0.333333 },
      ],
      updatedAt: now,
    },
  ],
  productStocks: [
    {
      productId: "prod-1",
      stock: 18,
      lowStockThreshold: 8,
      updatedAt: now,
    },
    {
      productId: "prod-2",
      stock: 12,
      lowStockThreshold: 8,
      updatedAt: now,
    },
  ],
  orders: [
    {
      id: "ord-1",
      code: "RC-3103-001",
      source: "web",
      locale: "id",
      customerName: "Nadia",
      customerWhatsapp: "628111111111",
      fulfillmentMethod: "pickup",
      preorderDate: "2026-03-31T14:00:00.000Z",
      note: "Tolong kasih pita merah kalau bisa.",
      deliveryFee: 0,
      subtotal: 52000,
      total: 52000,
      status: "payment_review",
      items: [
        {
          productId: "prod-1",
          productName: "Smoked Beef Mayo",
          variantType: "fried",
          variantLabel: "Fried",
          quantity: 2,
          pieceCount: 6,
          unitPrice: 30000,
          costSnapshot: 14160,
        },
        {
          productId: "prod-2",
          productName: "Choco Cheese",
          variantType: "frozen",
          variantLabel: "Frozen",
          quantity: 1,
          pieceCount: 3,
          unitPrice: 28000,
          costSnapshot: 10533,
        },
      ],
      paymentProof: {
        fileName: "sample-proof.jpg",
        mimeType: "image/jpeg",
        url:
          "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgZmlsbD0iI2ZlZjJmMiIvPjx0ZXh0IHg9IjUwIiB5PSIxNTAiIGZvbnQtc2l6ZT0iMzAiIGZpbGw9IiNiOTFlMWUiPkJ1a3RpIHRyYW5zZmVyIHNhbXBsZTwvdGV4dD48L3N2Zz4=",
        dataUrl:
          "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgZmlsbD0iI2ZlZjJmMiIvPjx0ZXh0IHg9IjUwIiB5PSIxNTAiIGZvbnQtc2l6ZT0iMzAiIGZpbGw9IiNiOTFlMWUiPkJ1a3RpIHRyYW5zZmVyIHNhbXBsZTwvdGV4dD48L3N2Zz4=",
        uploadedAt: now,
      },
      createdAt: "2026-03-31T08:50:00.000Z",
      updatedAt: "2026-03-31T08:50:00.000Z",
    },
    {
      id: "ord-2",
      code: "RC-3003-004",
      source: "web",
      locale: "id",
      customerName: "Tara",
      customerWhatsapp: "628222222222",
      fulfillmentMethod: "delivery",
      address: "Jl. Melati No. 12, Jakarta Selatan",
      preorderDate: "2026-03-30T12:00:00.000Z",
      note: "",
      deliveryFee: 10000,
      subtotal: 72000,
      total: 82000,
      status: "completed",
      items: [
        {
          productId: "prod-1",
          productName: "Smoked Beef Mayo",
          variantType: "frozen",
          variantLabel: "Frozen",
          quantity: 4,
          pieceCount: 12,
          unitPrice: 28000,
          costSnapshot: 14160,
        },
      ],
      createdAt: "2026-03-29T12:10:00.000Z",
      updatedAt: "2026-03-30T13:30:00.000Z",
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Order baru perlu dicek",
      body: "Nadia upload bukti bayar untuk RC-3103-001.",
      href: "/seller/orders",
      read: false,
      createdAt: "2026-03-31T08:55:00.000Z",
    },
  ],
  inventoryMovements: [],
};
